version: "3.0"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

  app:
    build: .
    container_name: node-app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongo-data:
